# Generated by Django 6.0.2 on 2026-02-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posters/', verbose_name='Poster Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('paper_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Paper Link')),
                ('github_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='GitHub Link')),
                ('description', models.TextField(verbose_name='Description')),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Validation Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Research Poster',
                'verbose_name_plural': 'Research Posters',
                'ordering': ['-created_at'],
            },
        ),
    ]
