# Generated by Django 6.0.2 on 2026-02-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchposter',
            name='why_useful',
            field=models.TextField(blank=True, null=True, verbose_name='Why Useful for the Research of the Group'),
        ),
    ]
