# Generated by Django 6.0.2 on 2026-02-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0002_researchposter_why_useful'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchposter',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Internal Notes'),
        ),
    ]
