# Generated by Django 6.0.2 on 2026-02-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0003_researchposter_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchposter',
            name='category',
            field=models.CharField(choices=[('ml', 'Machine Learning'), ('cv', 'Computer Vision'), ('nlp', 'Natural Language Processing'), ('robotics', 'Robotics'), ('hci', 'Human-Computer Interaction'), ('data_science', 'Data Science'), ('theory', 'Theory'), ('systems', 'Systems & Architecture'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='researchposter',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., deep learning, CNN, medical)', max_length=200, null=True, verbose_name='Tags'),
        ),
    ]
