# Generated by Django 6.0.2 on 2026-02-16 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0004_researchposter_category_researchposter_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchposter',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Favorite'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('status_changed', 'Status Changed'), ('favorited', 'Favorited'), ('unfavorited', 'Unfavorited')], max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
                ('poster_title', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='bot_engine.researchposter')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
