# Generated by Django 6.0.2 on 2026-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0005_researchposter_is_favorite_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='researchposter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='researchposter',
            name='subfields',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='authors',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='category',
            field=models.CharField(choices=[('ai_ml', 'AI & Machine Learning'), ('cv_graphics', 'Computer Vision & Graphics'), ('systems_arch', 'Systems & Architecture'), ('networks_security', 'Networks & Security'), ('data_info', 'Data & Information'), ('software_algo', 'Software & Algorithms'), ('computing_paradigms', 'Computing Paradigms'), ('interdisciplinary', 'Interdisciplinary & Applied'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='github_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='image',
            field=models.ImageField(upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='paper_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='why_useful',
            field=models.TextField(blank=True, null=True),
        ),
    ]
