# Generated by Django 6.0.2 on 2026-03-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0008_remove_researchposter_is_favorite_activitylog_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchposter',
            name='analysis_status',
            field=models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('processing', 'Processing')], default='ok', max_length=20),
        ),
    ]
