# Generated by Django 6.0.2 on 2026-03-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0010_researchposter_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchposter',
            name='upload_source',
            field=models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], default='web', max_length=20),
        ),
    ]
