# Generated by Django 6.0.2 on 2026-03-20 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0011_researchposter_upload_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='researchposter',
            name='analysis_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchposter',
            name='image_sha256',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='researchposter',
            name='last_failure_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchposter',
            name='last_success_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchposter',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchposter',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='researchposter',
            name='processing_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='analysis_status',
            field=models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed'), ('processing', 'Processing')], db_index=True, default='ok', max_length=20),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='upload_source',
            field=models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('whatsapp', 'WhatsApp')], db_index=True, default='web', max_length=20),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'timestamp'], name='bot_engine__action_ae829a_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['poster', 'timestamp'], name='bot_engine__poster__31ccf0_idx'),
        ),
        migrations.AddIndex(
            model_name='researchposter',
            index=models.Index(fields=['analysis_status', 'created_at'], name='bot_engine__analysi_fb35c6_idx'),
        ),
        migrations.AddIndex(
            model_name='researchposter',
            index=models.Index(fields=['upload_source', 'created_at'], name='bot_engine__upload__b4f166_idx'),
        ),
        migrations.AddIndex(
            model_name='researchposter',
            index=models.Index(fields=['validation_status', 'created_at'], name='bot_engine__validat_ae2819_idx'),
        ),
    ]
