# Generated by Django 6.0.2 on 2026-03-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0012_researchposter_analysis_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchposter',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
