# Generated by Django 6.0.2 on 2026-03-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0013_alter_researchposter_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchposter',
            name='category',
            field=models.CharField(choices=[('ai_ml', 'AI & Machine Learning'), ('cv_graphics', 'Computer Vision & Graphics'), ('systems_arch', 'Systems & Architecture'), ('networks_security', 'Networks & Security'), ('data_info', 'Data & Information'), ('software_algo', 'Software & Algorithms'), ('computing_paradigms', 'Computing Paradigms'), ('interdisciplinary', 'Interdisciplinary & Applied'), ('other', 'Other')], db_index=True, default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='researchposter',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
