# Generated by Django 6.0.2 on 2026-03-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0014_add_category_and_validation_status_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchposter',
            name='publication_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
