# Generated by Django 6.0.2 on 2026-04-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0015_add_publication_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchposter',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posters/thumbs/'),
        ),
    ]
