# Generated by Django 6.0.2 on 2026-04-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_engine', '0023_bot_account'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='botaccount',
            new_name='bot_engine__platfor_1a4655_idx',
            old_name='bot_engine__platfor_e2b4d3_idx',
        ),
    ]
